services:
  - type: web
    name: TechDevsV1
    env: node
    plan: free
    repo: https://github.com/Spiderman-Diaries/spiderman-v1.git
    branch: main
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: SESSION_ID
        sync: false
      - key: OWNER_NUMBER
        sync: false
